version: '3'
services:
  app:
    container_name: library_app
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/testdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - WAIT_FOR=postgres:5432
    depends_on:
      - db
    networks:
      - library_network
  db:
    container_name: library_db
    image: "postgres:12"
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    networks:
      - library_network
networks:
  library_network:
    driver: bridge
