version: '3'
services:
  app:
    container_name: book_sharing_app
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/book_sharing_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - WAIT_FOR=postgres:5432
    depends_on:
      - db
    networks:
      - book_sharing_network
  db:
    container_name: book_sharing_db
    image: "postgres:12"
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book_sharing_db
    networks:
      - book_sharing_network
networks:
  book_sharing_network:
    driver: bridge
